-- ==========================================================================
-- MIGRATION: Auto-cleanup is now handled server-side (server/workers/cleanup.js)
-- This file is kept for reference only. No SQL migration is needed.
--
-- The server cleanup worker runs every 10 minutes and:
--   1. Deletes expired job rows (older than 2 hours)
--   2. Removes corresponding files from all 3 storage buckets
--      (uploads, processed, thumbnails)
--
-- If you previously ran the pg_cron migration, disable it:
--   SELECT cron.unschedule('cleanup-expired-jobs');
--   DROP FUNCTION IF EXISTS public.cleanup_expired_jobs();
-- ==========================================================================
